### ISSUE TITLE
eID viewer crash on drag-and-drop

### ISSUE THREAD

**Issue by Wannes123** [Fedict/eid-viewer#4] opened 2017-06-19 12:11 UTC
Hi,

When using the 'drag-and-drop' feature in the eID viewer, before the identity card is fully read, the program crashes. Using eID viiewer version 4.2.8 on windows 8 64bit.

Grts,
Wannes

**Comment by Frederikus** [comment] 2017-06-19 12:22
Hello,

Thank you for reporting this issue.
I've just tested this and can reproduce it.

I'll fix this (will be in version 4.2.10, as 4.2.9 of the viewer will be out this week)

**Comment by Wannes123** [comment] 2017-06-19 12:36
Hi,

Thank you for your quick response.

Any idea when version 4.2.10 will be released ? 

Also, will there be an install file available for this version?

Thanks,
Wannes Schols

**Comment by Frederikus** [comment] 2017-06-19 12:48
Hello Wannes,

I can't commit to any 4.2.10 release date yet. (Is this bug something you run into often?)
With install file, you mean msi installer? (like the ones you see when you click on "Download eID software for another operating system")

**Comment by Wannes123** [comment] 2017-06-19 13:26
Hi,

We plan to be using the drag-and-drop to register customers entering offices of the  Christelijke Mutualiteit (CM), so we anticipate the clerks will run into this issue a lot.

Yes, I mean an msi isntaller.

Thanks,
Wannes

**Comment by Frederikus** [comment] 2017-06-20 12:17
Hello,

I made a fix for this (viewer will only do drag and drop when all data is available).

We do still release msi installers, although the latest version of the NSIS installer can also be installed silently (using the /S parameter)
e.g. in a .bat file:
start /wait /b "" "Belgium eID-QuickInstaller 4.2.6.3238.exe" /S
start /wait /b "" "Belgium eID Viewer Installer 4.2.6.3238.exe" /S

**Comment by Frederikus** [comment] 2017-06-20 12:17
Fix will be in the 4.2.9 release

**Comment by Wannes123** [comment] 2017-06-20 12:21
Thank you very much Frederikus!

**Comment by yoe** [comment] 2017-06-20 12:25
Side note: this repository contains the old version of the eID viewer (the Java implementation) that was replaced with the 4.2 version of the middleware and viewer.

I've opened an issue there (referring to this one), and will close this one right now, since it's in the wrong place ;-)

Thanks for reporting

**Closed as completed by yoe** 2017-06-20 12:25 UTC
Labels: bug

**Comment by Wannes123** [comment] 2017-06-20 12:26
Can you point me to the other repository?

Thanks!

**Comment by Frederikus** [comment] 2017-06-20 12:28
The eID Viewer code is placed within the https://github.com/Fedict/eid-mw
project now (since version 4.2)

Wkr,
 Frederik
